services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: node:22.15.0-alpine3.21
    tty: true
    volumes:
      - type: bind
        source: ./src
        target: /app
    ports:
      - ${FRONTEND_PORT:-5173}:5173
    working_dir: /app
    user: node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
